export type Priority = "ALTA" | "MÉDIA" | "BAIXA";

export type Topic = { id: string; name: string; priority: Priority };
export type Subject = { id: string; name: string; shortName: string; topics: Topic[] };

const topics = (subjectId: string, rows: [string, Priority][]): Topic[] =>
  rows.map(([name, priority], index) => ({ id: `${subjectId}-${index + 1}`, name, priority }));

export const curriculum: Subject[] = [
  { id: "portugues", name: "Língua Portuguesa", shortName: "Português", topics: topics("portugues", [
    ["Compreensão e interpretação de textos.", "ALTA"],
    ["Tipologia textual.", "MÉDIA"],
    ["Ortografia oficial.", "MÉDIA"],
    ["Acentuação gráfica.", "ALTA"],
    ["Emprego das classes de palavras.", "MÉDIA"],
    ["Emprego do sinal indicativo de crase.", "ALTA"],
    ["Sintaxe da oração e do período.", "ALTA"],
    ["Pontuação.", "ALTA"],
    ["Concordância nominal e verbal.", "ALTA"],
    ["Regência nominal e verbal.", "ALTA"],
    ["Significação das palavras.", "MÉDIA"],
  ])},
  { id: "historia", name: "História do Brasil", shortName: "História", topics: topics("historia", [
    ["Descobrimento do Brasil (1500).", "BAIXA"],
    ["Brasil Colônia (1530-1815): Capitanias Hereditárias, Economia, Extrativismo Vegetal, Extrativismo Mineral, Pecuária, Escravidão, Organização Po Expansão Territorial.", "MÉDIA"],
    ["Independência do Brasil (1822): a Nomeação do Príncipe Regente D. Pedro I, Dia do Fico, Reconhecimento da Independência do Brasil.", "MÉDIA"],
    ["Primeiro Reinado (1822-1831).", "MÉDIA"],
    ["Segundo Reinado (1831-1840).", "MÉDIA"],
    ["Primeira República (1889-1930): o Primeiro Governo Provisório, Assembleia Constituinte, Presidência de Deodoro da Fonseca, a Política dos Governadores, o Coronelismo, Movimentos Tenentistas, Coluna Prestes, Revolta da Armada.", "ALTA"],
    ["Revolução de 1930.", "ALTA"],
    ["Era Vargas (1930-1945).", "ALTA"],
    ["Os Presidentes do Brasil de 1964 à atualidade.", "ALTA"],
    ["História da Bahia.", "ALTA"],
    ["Independência da Bahia.", "ALTA"],
    ["Revolta de Canudos.", "ALTA"],
    ["Revolta dos Malês.", "ALTA"],
    ["Conjuração Baiana.", "ALTA"],
    ["Sabinada.", "ALTA"],
  ])},
  { id: "geografia", name: "Geografia do Brasil", shortName: "Geografia", topics: topics("geografia", [
    ["Relevo brasileiro.", "MÉDIA"],
    ["Urbanização: crescimento urbano, problemas estruturais, contingente populacional brasileiro.", "ALTA"],
    ["Tipos de fontes de energia que participam da matriz energética brasileira: eólica, hidráulica, biomassa, solar e a das marés.", "MÉDIA"],
    ["Problemas Ambientais.", "MÉDIA"],
    ["Clima: pressão atmosférica, umidade, temperatura, fatores que determinam o clima, mudanças climáticas e as suas consequências.", "MÉDIA"],
    ["Geografia da Bahia: aspectos políticos, físicos, econômicos, sociais e culturais.", "ALTA"],
  ])},
  { id: "matematica", name: "Matemática", shortName: "Matemática", topics: topics("matematica", [
    ["Conjuntos numéricos: Números Naturais, Inteiros, Racionais, Reais e Complexos (forma algébrica e forma trigonométrica). Operações, propriedades e aplicações. Sequências numéricas, progressão aritmética e progressão geométrica.", "MÉDIA"],
    ["Álgebra: Expressões algébricas. Polinômios: operações e propriedades. Equações polinomiais e inequações relacionadas.", "BAIXA"],
    ["Funções: generalidades. Funções elementares: 1º grau, 2º grau, modular, exponencial e logarítmica, gráficos. Propriedades.", "ALTA"],
    ["Sistemas lineares, Matrizes e Determinantes: Propriedades, aplicações.", "MÉDIA"],
    ["Análise Combinatória: Arranjos, Permutações e Combinações simples, Binômio de Newton e Probabilidade em espaços amostrais finitos.", "ALTA"],
    ["Geometria e Medidas: Geometria plana: figuras geométricas, congruência, semelhança, perímetro e área. Geometria espacial: paralelismo, perpendicularismo entre retas e planos, áreas e volumes dos sólidos geométricos: prisma, pirâmide, cilindro, cone e esfera. Geometria analítica no plano: retas, circunferência e distâncias.", "MÉDIA"],
    ["Trigonometria: razões trigonométricas, funções, fórmulas de transformações trigonométricas, equações e triângulos.", "MÉDIA"],
  ])},
  { id: "atualidades", name: "Atualidades", shortName: "Atualidades", topics: topics("atualidades", [
    ["Globalização: conceitos, efeitos e implicações sociais, econômicas, políticas e culturais.", "ALTA"],
    ["Multiculturalidade, Pluralidade e Diversidade Cultural.", "MÉDIA"],
    ["Tecnologias de Informação e Comunicação: conceitos, efeitos e implicações sociais, econômicas, políticas e culturais.", "MÉDIA"],
  ])},
  { id: "informatica", name: "Informática", shortName: "Informática", topics: topics("informatica", [
    ["Conceitos e modos de utilização de aplicativos para edição de textos (Word, Writer), planilhas (Excel, Calc), apresentações (PowerPoint, Impress); Microsoft Office (versão 2007 e superiores), LibreOffice (versão 5.0 e superiores).", "ALTA"],
    ["Sistemas operacionais Windows 7, Windows 10 e Linux.", "ALTA"],
    ["Organização e gerenciamento de informações, arquivos, pastas e programas.", "ALTA"],
    ["Atalhos de teclado, ícones, área de trabalho e lixeira.", "ALTA"],
    ["Conceitos básicos e modos de utilização de tecnologias, ferramentas, aplicativos e procedimentos associados à Internet e intranet.", "ALTA"],
    ["Correio eletrônico.", "MÉDIA"],
    ["Computação em nuvem.", "MÉDIA"],
  ])},
  { id: "constitucional", name: "Direito Constitucional", shortName: "Constitucional", topics: topics("constitucional", [
    ["Constituição da República Federativa do Brasil.", "ALTA"],
    ["Dos princípios fundamentais.", "ALTA"],
    ["Dos Direitos e garantias fundamentais.", "ALTA"],
    ["Da organização do Estado.", "MÉDIA"],
    ["Da Administração Pública.", "MÉDIA"],
    ["Dos militares dos Estados, do Distrito Federal e dos Territórios.", "ALTA"],
    ["Da Segurança Pública.", "ALTA"],
    ["Constituição do Estado da Bahia.", "MÉDIA"],
    ["Dos princípios fundamentais.", "MÉDIA"],
    ["Direitos e garantias fundamentais.", "ALTA"],
    ["Dos Servidores Públicos Militares.", "MÉDIA"],
    ["Da Segurança Pública.", "ALTA"],
  ])},
  { id: "humanos", name: "Direitos Humanos", shortName: "Direitos Humanos", topics: topics("humanos", [
    ["A Declaração Universal dos Direitos Humanos/1948.", "ALTA"],
    ["Convenção Americana sobre Direitos Humanos/1969 (Pacto de São José da Costa Rica) (art. 1º ao 32).", "ALTA"],
    ["Pacto Internacional dos Direitos Econômicos, Sociais e Culturais (art. 1º ao 15).", "MÉDIA"],
    ["Declaração de Pequim Adotada pela Quarta Conferência Mundial sobre as Mulheres: Ação para Igualdade, Desenvolvimento e Paz.", "ALTA"],
  ])},
  { id: "administrativo", name: "Direito Administrativo", shortName: "Administrativo", topics: topics("administrativo", [
    ["Administração Pública.", "ALTA"],
    ["Princípios fundamentais da administração pública.", "ALTA"],
    ["Poderes e deveres dos administradores públicos: uso e abuso do poder, poderes vinculado, discricionário, hierárquico, disciplinar e regulamentar, poder de polícia, deveres dos administradores públicos.", "ALTA"],
    ["Servidores públicos: cargo, emprego e função públicos.", "MÉDIA"],
    ["Regime jurídico do militar estadual: Estatuto dos Policiais Militares do Estado da Bahia (Lei estadual nº 7.990, de 27 de dezembro de 2001 - arts. 1º ao 59).", "MÉDIA"],
  ])},
  { id: "penal", name: "Direito Penal", shortName: "Direito Penal", topics: topics("penal", [
    ["Do crime.", "ALTA"],
    ["Elementos.", "ALTA"],
    ["Consumação e tentativa.", "ALTA"],
    ["Desistência voluntária e arrependimento eficaz.", "MÉDIA"],
    ["Arrependimento posterior.", "MÉDIA"],
    ["Crime impossível.", "MÉDIA"],
    ["Causas de exclusão de ilicitude e culpabilidade.", "ALTA"],
    ["Contravenção.", "BAIXA"],
    ["Dos crimes contra a vida (homicídio, lesão corporal, rixa).", "ALTA"],
    ["Dos crimes contra a liberdade pessoal (constrangimento ilegal, ameaça, perseguição, sequestro e cárcere privado).", "ALTA"],
    ["Dos crimes contra o patrimônio (furto, roubo, extorsão, apropriação indébita, receptação).", "ALTA"],
    ["Dos crimes contra a dignidade sexual (estupro, importunação sexual, assédio sexual).", "MÉDIA"],
    ["Corrupção ativa.", "ALTA"],
    ["Corrupção passiva.", "ALTA"],
    ["Lei nº 9.455, de 07 de abril de 1997 (Crimes de tortura).", "MÉDIA"],
  ])},
  { id: "igualdade", name: "Igualdade Racial e de Gênero", shortName: "Igualdade Racial", topics: topics("igualdade", [
    ["Constituição da República Federativa do Brasil (art. 1º, 3º, 4º e 5º).", "ALTA"],
    ["Constituição do Estado da Bahia, (Cap. XXIII ‘Do Negro’).", "MÉDIA"],
    ["Lei nº 12.288, de 20 de julho de 2010 (Estatuto da Igualdade Racial).", "MÉDIA"],
    ["Lei nº 7.716, de 5 de janeiro de 1989 (Define os crimes resultantes de preconceito de raça ou de cor) e Lei nº 9.459, de 13 de maio de 1997 (Tipificação dos crimes resultantes de preconceito de raça ou de cor).", "ALTA"],
    ["Decreto nº 65.810, de 08 de dezembro de 1969 (Convenção internacional sobre a eliminação de todas as formas de discriminação racial).", "MÉDIA"],
    ["Decreto nº 4.377, de 13 de setembro de 2002 (Convenção sobre a eliminação de todas as formas de discriminação contra a mulher).", "MÉDIA"],
    ["Lei nº 11.340, de 7 de agosto de 2006 (Lei Maria da Penha).", "ALTA"],
    ["Código Penal Brasileiro (art. 140).", "ALTA"],
    ["Lei nº 9.455, de 7 de abril de 1997 (Crime de Tortura).", "MÉDIA"],
    ["Lei nº 7.437, de 20 de dezembro de 1985 (Lei Caó).", "MÉDIA"],
    ["Lei Estadual nº 10.549, de 28 de dezembro de 2006 (Secretaria de Promoção da Igualdade Racial).", "MÉDIA"],
    ["Lei nº 10.678, de 23 de maio de 2003 (Secretaria de Políticas de Promoção da Igualdade Racial da Presidência da República).", "MÉDIA"],
  ])},
  { id: "penal-militar", name: "Direito Penal Militar", shortName: "Penal Militar", topics: topics("penal-militar", [
    ["Dos crimes contra a autoridade ou disciplina militar: motim, revolta, conspiração, aliciação para motim ou revolta.", "ALTA"],
    ["Da violência contra superior ou militar de serviço.", "MÉDIA"],
    ["Desrespeito a superior.", "MÉDIA"],
    ["Recusa de obediência.", "MÉDIA"],
    ["Reunião ilícita.", "MÉDIA"],
    ["Publicação ou crítica indevida.", "MÉDIA"],
    ["Resistência mediante ameaça ou violência.", "ALTA"],
    ["Dos crimes contra o serviço militar e o dever militar: deserção, abandono de posto, descumprimento de missão, embriaguez em serviço, dormir em serviço.", "ALTA"],
    ["Crimes contra a Administração Militar: desacato a superior, desacato a militar, desobediência, peculato, peculato-furto, concussão.", "ALTA"],
    ["Dos crimes contra o dever funcional: prevaricação.", "MÉDIA"],
  ])},
];

export const allTopics = curriculum.flatMap((subject) =>
  subject.topics.map((topic) => ({ ...topic, subject }))
);
